### PR TITLE
Update add-on configuration for Supervisor 2021.2

### PR DESCRIPTION
**Pull request by clau-bucur**
I can't test it with my own repo.
If acceptable, I'll test it once it's merged.

### CODE REVIEW

**Comment by yozik04** [comment]
I am almost sure LIMITS won't validate.

**Comment by yozik04** [comment]
@clau-bucur You need to make a valid json. Test here: https://jsonformatter.curiousconcept.com/

**Comment by clau-bucur** [comment]
Checking

**Comment by clau-bucur** [comment]
LIMITS validate correctly. I've fixed LOGGING_LEVEL and improved others.

**Pull request merged**
