### PR TITLE
Add the rest of PAI configs to addon schema

### PR DESCRIPTION
**Pull request by clau-bucur**
Added the rest of the PAI configs to addon schema.
Should help with the remaining issues on https://github.com/ParadoxAlarmInterface/pai/issues/199

### CODE REVIEW

**Comment by yozik04** [comment]
Is this ready for merging?

**Comment by clau-bucur** [comment]
Tested locally and ready for merge.

**Comment by clau-bucur** [comment]
@yozik04 here's the generated options.json file as per your request:
```
{
  "LOGGING_LEVEL_CONSOLE": 20,
  "LOGGING_LEVEL_FILE": 40,
  "CONNECTION_TYPE": "IP",
  "SERIAL_PORT": "/dev/ttyUSB0",
  "SERIAL_BAUD": 9600,
  "IP_CONNECTION_HOST": "xxx",
  "IP_CONNECTION_PORT": 10000,
  "IP_CONNECTION_PASSWORD": "xxx",
  "KEEP_ALIVE_INTERVAL": 10,
  "LIMITS": {
    "zone": "auto",
    "user": "1-2",
    "door": "",
    "pgm": "1-5",
    "partition": "auto",
    "module": "1-2",
    "repeater": "",
    "keypad": "1-2",
    "key-switch": "1-3"
  },
  "SYNC_TIME": true,
  "SYNC_TIME_MIN_DRIFT": 60,
  "PASSWORD": "0000",
  "MQTT_ENABLE": true,
  "MQTT_HOST": "core-mosquitto",
  "MQTT_PORT": 1883,
  "MQTT_KEEPALIVE": 60,
  "MQTT_USERNAME": "xxx",
  "MQTT_PASSWORD": "xxx",
  "MQTT_HOMEASSISTANT_AUTODISCOVERY_ENABLE": true,
  "COMMAND_ALIAS": {        
    "arm": "partition all arm",
    "disarm": "partition all disarm"
  },                        
  "MQTT_COMMAND_ALIAS": {   
    "armed_home": "arm_stay",
    "armed_night": "arm_sleep",
    "armed_away": "arm",    
    "disarmed": "disarm"    
  },                        
  "HOMEASSISTANT_NOTIFICATIONS_EVENT_FILTERS": [
    "live,alarm,-restore",  
    "live,trouble,-clock",  
    "live,tamper"           
  ],                        
  "PUSHBULLET_CONTACTS": [],
  "PUSHBULLET_EVENT_FILTERS": [
    "live,alarm,-restore",  
    "live,trouble,-clock",  
    "live,tamper"           
  ],                        
  "PUSHOVER_EVENT_FILTERS": [
    "live,alarm,-restore",  
    "live,trouble,-clock",  
    "live,tamper"           
  ],                        
  "SIGNAL_CONTACTS": [],    
  "SIGNAL_EVENT_FILTERS": [ 
    "live,alarm,-restore",  
    "live,trouble,-clock",  
    "live,tamper"           
  ],                        
  "GSM_CONTACTS": [],       
  "GSM_EVENT_FILTERS": [    
    "live,alarm,-restore",  
    "live,trouble,-clock",  
    "live,tamper"           
  ],                        
  "IP_INTERFACE_ENABLE": false,
  "IP_INTERFACE_PASSWORD": "paradox",
  "DUMMY_EVENT_FILTERS": [],
  "MQTT_PUBLISH_COMMAND_STATUS": true,
  "MQTT_PUBLISH_RAW_EVENTS": false
}
```

**Comment by yozik04** [comment]
Thank you @clau-bucur
That is a great help!

**Comment by clau-bucur** [comment]
Glad I could help this awesome project!

**Comment by kobusdbr** [comment]
Apologies for the dumb question but what do I do with this options.json file?

**Comment by yozik04** [comment]
@kobusdbr It is not for you =) It is for me...

**Comment by kobusdbr** [comment]
> @kobusdbr It is not for you =) It is for me...

ok thank you. just making sure I am following this correctly and not missing anything because mine is not working. Will there be another update?

**Pull request merged**
